name: Test and Deploy back-end changes to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DYNAMODB_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DYNAMODB_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test lambda function
        id: test_lambda
        run: pip install -r backend/requirements.txt && python3 backend/test_lambda.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.2

      - name: Terraform Init
        working-directory: infra/
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/
        run: terraform validate

      - name: Terraform Apply
        working-directory: infra/
        run: terraform apply -input=false
        env:
          TF_CLI_ARGS: "-auto-approve"
